management:
  endpoints:
#    jmx:
#      exposure:
#        include: health,info,newendpoint
    web:
      base-path: /manage
      exposure:
        include: health,info,newendpoint,jolokia
  info:
    build:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
#spring:
#  jmx:
#    enabled: true
server:
  servlet:
    context-path: /myapp
